### ISSUE TITLE
Source of inspiration, Adobe official web version

### ISSUE THREAD

**Issue by S7venLights** [chase-manning/react-photo-studio#134]
Hi, I'm really exited for your webapp and what it could mean for Photoshop on linux.

I came across this:
https://www.makeuseof.com/use-adobe-photoshop-free-on-web/
 https://creativecloud.adobe.com/cc/photoshop

And wondered if it could help you in developement of your app. 
It's Adobes official fuller featured online photoshop in the works. 

I also wonder if the official version could be made to work privately offline similar to these Photopea projects: 
https://github.com/DUOLabs333/photopea
https://github.com/spooknik/Photopea-Appimage
https://github.com/FindIndex/Photopea-Offline

Obviously your version would be more private than an official Adobe version so I'm still keen to see it mature. I would help code if I knew how but otherwise happy to test.

**Comment by chase-manning** [comment]
Hi there! Thanks for reaching out 😄 

Wow, I didn't know Photoshop was working on their own online version, that is super cool!
Glad they are working on this and it looks really good!

Yes it should be easy to make this run privately offline.
There is a popular tool called [Electron](https://www.electronjs.org/) which allows you to turn a website into a desktop app, and it works on Linux.
Lots of popular apps are built with this including:
- Visual Studio Code
- WhatsApp
- Twitch
- Slack
- InVision

Thanks so much for offering to help out!

I think however I probably won't be investing time in continuing with this project unfortunately.
The reason being that it is a massive undertaking, would take probably around a year of mostly full time work to get it into a state where it's powerful enough to have general use and marketability.
And with Photoshop building their own version, and Photopea doing so well, it would likely be tough to compete against them for any meaningful market share.

**Comment by S7venLights** [comment]
I get that… its unfortunate. Would be cool if many developers knew about this and it became like Blender or OBS.  But yeah maybe you could be the one to start the official photoshop offline electron app dunno? ¯\_(ツ)_/¯

**Comment by chase-manning** [comment]
Closing this issue for now as an Electron app is out of scope at this time, and probably best done as a separate project 😄
